# Generated by Django 2.2 on 2019-04-08 07:55

from django.db import migrations, models
import django.db.models.deletion
import identity.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0003_auto_20190408_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerphoto', models.ImageField(upload_to=identity.models.upload_image)),
                ('passengerpassport', models.ImageField(upload_to=identity.models.upload_image)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.Agent')),
            ],
        ),
    ]
