# Generated by Django 2.2 on 2019-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycheck',
            name='passengerpassport',
            field=models.ImageField(upload_to='media/check/'),
        ),
        migrations.AlterField(
            model_name='identitycheck',
            name='passengerphoto',
            field=models.ImageField(upload_to='media/check/'),
        ),
    ]
