# Generated by Django 2.2 on 2019-04-08 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import identity.models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_auto_20190408_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycheck',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='identitycheck',
            name='passengerpassport',
            field=models.ImageField(upload_to=identity.models.upload_image),
        ),
        migrations.AlterField(
            model_name='identitycheck',
            name='passengerphoto',
            field=models.ImageField(upload_to=identity.models.upload_image),
        ),
    ]
