# Generated by Django 2.2 on 2019-05-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20190408_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitycheck',
            name='ableToBoard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='identitycheck',
            name='birthDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='identitycheck',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identitycheck',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='identitycheck',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='identitycheck',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
