# Generated by Django 2.2 on 2019-05-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20190501_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identitycheck',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='identitycheck',
            old_name='passengerpassport',
            new_name='passengerPassport',
        ),
        migrations.RenameField(
            model_name='identitycheck',
            old_name='passengerphoto',
            new_name='passengerPhoto',
        ),
    ]
