# Generated by Django 2.2 on 2019-05-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_auto_20190501_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycheck',
            name='birthDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
