# Generated by Django 2.2 on 2019-04-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_auto_20190412_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanted',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='wanted',
            name='updated',
        ),
    ]
