# Generated by Django 2.2 on 2019-04-21 12:21

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20190419_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='media/passengers/'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/passenger/'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='encodings',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
    ]
