# Generated by Django 2.2 on 2019-05-01 16:22

from django.db import migrations, models
import django_postgres_extensions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_auto_20190421_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wanted',
            name='encodings',
            field=django_postgres_extensions.models.fields.ArrayField(base_field=models.FloatField(), blank=True, default=list, null=True, size=None),
        ),
    ]
