# Generated by Django 2.2 on 2019-05-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_auto_20190430_0907'),
        ('models', '0013_auto_20190502_2231'),
    ]

    operations = [
    ]
